# Generated by Django 2.2.12 on 2021-09-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0020_allow_blank_submitterip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maprenderingjob',
            index=models.Index(fields=['submission_time'], name='maposmatic__submiss_0f8f5e_idx'),
        ),
    ]
