# Generated by Django 2.2.12 on 2021-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0021_submission_time_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='job',
            field=models.ManyToManyField(related_name='uploads', to='maposmatic.MapRenderingJob'),
        ),
    ]
