# Generated by Django 2.2.12 on 2022-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0023_no_NULL_maptitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprenderingjob',
            name='queue',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
