# Generated by Django 4.0.7 on 2022-08-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0023_no_NULL_maptitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprenderingjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
