# Generated by Django 2.2.12 on 2022-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0024_maprenderingjob_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprenderingjob',
            name='indexer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.RunSQL("UPDATE maposmatic_maprenderingjob SET indexer = 'Street' WHERE layout LIKE '%index%'"),
    ]
