# Generated by Django 2.2.12 on 2022-10-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0027_maprenderingjob_indexer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprenderingjob',
            name='indexer',
            field=models.CharField(default='Street', max_length=256, null=True),
        ),
    ]
