# Generated by Django 2.2.12 on 2023-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0029_add_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprenderingjob',
            name='map_language',
            field=models.CharField(default='en_US.UTF-8', max_length=16),
        ),
    ]
