# Generated by Django 2.2.12 on 2023-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0030_map_language_default_engish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maprenderingjob',
            name='map_language',
            field=models.CharField(blank=True, default='en_US.UTF-8', max_length=16, null=True),
        ),
    ]
