# Generated by Django 4.2.4 on 2023-08-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0031_allow_NULL_mal_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='maprenderingjob',
            name='extra_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
