# Generated by Django 4.2.4 on 2023-09-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maposmatic', '0033_uploadfile_keep_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
